#!/usr/bin/env python3
"""Generate current_furni.sql: items_base rows and shop pages for current Habbo furni the 2022 catalog lacks.

Inputs (from the asset workflow in the README):
  FURNIDATA   FurnitureData.json converted from habbo.com's current furnidata.xml
  BASE_NAMES  item_name of every existing items_base row, one per line
  CONVERTED   directory of converted .nitro files; furni without one are skipped

  python3 gen_current_furni.py FURNIDATA BASE_NAMES CONVERTED > current_furni.sql

ids are derived from Habbo's own furni id, so re-running gives the same rows:
floor = 1_000_000 + id, wall = 1_500_000 + id (floor and wall ids overlap in furnidata).
"""
import json
import os
import sys
from collections import defaultdict

FLOOR_BASE, WALL_BASE = 1_000_000, 1_500_000
PARENT_PAGE = 60000          # "Newer Furni", under the Furni tab (page 2)
FURNI_TAB = 2
ICON = 263                   # the Furni tab's own icon


def q(s):
    return "'" + str(s).replace("\\", "\\\\").replace("'", "\\'") + "'"


def main(furnidata, base_names, converted):
    fd = json.load(open(furnidata, encoding="utf-8"))
    have = {l.strip().lower() for l in open(base_names, encoding="utf-8") if l.strip()}
    nitro = {f[:-6] for f in os.listdir(converted) if f.endswith(".nitro")}

    rows, by_line, skipped = [], defaultdict(list), 0
    for section, kind, base in (("roomitemtypes", "s", FLOOR_BASE), ("wallitemtypes", "i", WALL_BASE)):
        for f in fd[section]["furnitype"]:
            cn = f["classname"]
            if cn.lower() in have:
                continue
            if cn.split("*")[0] not in nitro:
                skipped += 1
                continue
            item_id = base + f["id"]
            walk = int(bool(f.get("canstandon")))
            rows.append((item_id, f["id"], (f.get("name") or cn)[:56], cn, kind,
                         max(1, int(f.get("xdim") or 1)), max(1, int(f.get("ydim") or 1)),
                         # furnidata has no heights: walkable furni stack at 0, the rest at 1
                         0.0 if (walk or kind == "i") else 1.0,
                         int(bool(f.get("cansiton"))), int(bool(f.get("canlayon"))), walk))
            by_line[f.get("furniline") or "misc"].append((item_id, cn))

    out = [
        "-- Generated by gen_current_furni.py: current Habbo furni missing from the 2022 catalog.",
        "-- Behaviour data (interaction types, state counts) isn't in furnidata, so these are plain furni.",
        f"-- {len(rows)} furni in {len(by_line)} pages; {skipped} furnidata entries skipped (no converted file).",
        "SET NAMES utf8mb4;",
        "START TRANSACTION;",
        f"DELETE FROM catalog_items WHERE page_id BETWEEN {PARENT_PAGE} AND {PARENT_PAGE + 999};",
        f"DELETE FROM catalog_pages WHERE id BETWEEN {PARENT_PAGE} AND {PARENT_PAGE + 999};",
        f"DELETE FROM items_base WHERE id BETWEEN {FLOOR_BASE} AND {WALL_BASE + 999_999}"
        " AND id NOT IN (SELECT item_id FROM (SELECT DISTINCT item_id FROM items) owned);",
    ]
    for i in range(0, len(rows), 500):
        vals = ",\n".join(
            f"({r[0]},{r[1]},{q(r[2])},{q(r[3])},{q(r[4])},{r[5]},{r[6]},{r[7]:.2f},1,{r[8]},{r[9]},{r[10]},1,1,0,1,1)"
            for r in rows[i:i + 500])
        out.append(
            "INSERT IGNORE INTO items_base (id,sprite_id,public_name,item_name,type,width,length,stack_height,"
            "allow_stack,allow_sit,allow_lay,allow_walk,allow_gift,allow_trade,allow_recycle,"
            f"allow_marketplace_sell,allow_inventory_stack) VALUES\n{vals};")

    out.append(
        "INSERT INTO catalog_pages (id,parent_id,caption_save,caption,page_layout,icon_color,icon_image,min_rank,"
        f"order_num,visible,enabled,club_only) VALUES ({PARENT_PAGE},{FURNI_TAB},'newer_furni','Newer Furni',"
        f"'default_3x3',1,{ICON},1,999,'1','1','0');")
    for n, line in enumerate(sorted(by_line), start=1):
        page = PARENT_PAGE + n
        caption = line.replace("_", " ").title()[:64]
        out.append(
            "INSERT INTO catalog_pages (id,parent_id,caption_save,caption,page_layout,icon_color,icon_image,"
            f"min_rank,order_num,visible,enabled,club_only) VALUES ({page},{PARENT_PAGE},{q(line[:64])},"
            f"{q(caption)},'default_3x3',1,{ICON},1,{n},'1','1','0');")
        vals = ",\n".join(f"({q(item_id)},{page},{q(cn)},3,0,0,1,{k})"
                          for k, (item_id, cn) in enumerate(by_line[line], start=1))
        out.append("INSERT INTO catalog_items (item_ids,page_id,catalog_name,cost_credits,cost_points,"
                   f"points_type,amount,order_number) VALUES\n{vals};")
    out.append("COMMIT;")
    print("\n".join(out))
    print(f"{len(rows)} furni, {len(by_line)} pages, {skipped} skipped", file=sys.stderr)


if __name__ == "__main__":
    main(*sys.argv[1:4])
